services:
  awr-pg:
    image: postgres:14.17-alpine
    container_name: awr-be-project-pg
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=awr
    ports:
      - 5432:5432
    networks:
      - awr-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d awr']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  awr-network:
    name: awr-network
    driver: bridge
